# Generated by Django 5.1.15 on 2026-05-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('date', models.DateField(verbose_name='fecha del evento')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='ubicación')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='event_covers/', verbose_name='imagen de portada')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('upcoming', 'Próximo'), ('live', 'En vivo'), ('public_closed', 'Galería cerrada'), ('searchable_only', 'Sólo búsqueda'), ('archived', 'Archivado'), ('pending_deletion', 'Pendiente de borrado'), ('deleted', 'Borrado')], default='draft', max_length=32, verbose_name='estado')),
                ('visibility', models.CharField(choices=[('public', 'Público — listado en home'), ('unlisted', 'No listado — accesible por URL'), ('private', 'Privado — solo admin')], default='public', max_length=16, verbose_name='visibilidad')),
                ('public_until', models.DateTimeField(blank=True, help_text='Después de esta fecha la galería pública se cierra.', null=True, verbose_name='público hasta')),
                ('searchable_until', models.DateTimeField(blank=True, help_text='Después de esta fecha solo el admin puede buscar.', null=True, verbose_name='búsquedas habilitadas hasta')),
                ('archive_until', models.DateTimeField(blank=True, help_text='Después de esta fecha el evento se borra (R2 + DB).', null=True, verbose_name='archivado hasta')),
                ('permanent_archive', models.BooleanField(default=False, help_text='Si está activado, el evento NUNCA cambia de estado por retención. Para organizadores que pagan por archivo permanente.', verbose_name='archivo permanente')),
                ('photo_count', models.PositiveIntegerField(default=0, verbose_name='fotos totales')),
                ('pending_count', models.PositiveIntegerField(default=0, verbose_name='fotos pendientes')),
                ('photographer_count', models.PositiveIntegerField(default=0, verbose_name='fotógrafos')),
                ('search_count', models.PositiveIntegerField(default=0, verbose_name='búsquedas realizadas')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='descargas de ZIP')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['status', '-date'], name='event_status_date_idx'), models.Index(fields=['visibility', 'status'], name='event_vis_status_idx')],
            },
        ),
    ]
