# Generated by Django 5.1.15 on 2026-06-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("upcoming", "Próximo"),
                    ("live", "Galería abierta"),
                    ("public_closed", "Galería cerrada"),
                    ("searchable_only", "Sólo búsqueda"),
                    ("archived", "Archivado"),
                    ("pending_deletion", "Pendiente de borrado"),
                    ("deleted", "Borrado"),
                ],
                default="draft",
                max_length=32,
                verbose_name="estado",
            ),
        ),
    ]
