# Generated by Django 5.1.15 on 2026-06-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='portada (R2)'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_facebook',
            field=models.CharField(blank=True, default='', help_text='Usuario o link completo de la página.', max_length=200, verbose_name='Facebook del organizador'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_instagram',
            field=models.CharField(blank=True, default='', help_text='Usuario (@evento) o link completo.', max_length=200, verbose_name='Instagram del organizador'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='organizador'),
        ),
    ]
