# Generated by Django 5.1.15 on 2026-05-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('matched_photo_count', models.PositiveIntegerField(default=0, verbose_name='fotos encontradas')),
                ('deleted_photo_count', models.PositiveIntegerField(default=0, verbose_name='fotos borradas')),
                ('deleted_embedding_count', models.PositiveIntegerField(default=0, verbose_name='embeddings borrados')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completada'), ('failed', 'Falló')], default='pending', max_length=16, verbose_name='estado')),
                ('requester_ip_hash', models.CharField(help_text='Para rate-limiting sin guardar IP cruda.', max_length=64, verbose_name='hash de IP solicitante (sha256)')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completada el')),
                ('error_message', models.TextField(blank=True, verbose_name='mensaje de error')),
            ],
            options={
                'verbose_name': 'solicitud de borrado de datos',
                'verbose_name_plural': 'solicitudes de borrado de datos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='del_status_ts_idx'), models.Index(fields=['requester_ip_hash'], name='del_iphash_idx')],
            },
        ),
    ]
