# Generated by Django 5.1.15 on 2026-05-21 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('photographer_name', models.CharField(max_length=255, verbose_name='nombre')),
                ('photographer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('photographer_phone', models.CharField(blank=True, help_text='Para mandar el link por WhatsApp.', max_length=20, verbose_name='teléfono')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='hash del token (sha256)')),
                ('expires_at', models.DateTimeField(verbose_name='expira el')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revocado el')),
                ('revoked_reason', models.CharField(blank=True, max_length=255, verbose_name='motivo de revocación')),
                ('photo_limit', models.PositiveIntegerField(blank=True, help_text='Nulo = sin límite.', null=True, verbose_name='límite de fotos')),
                ('photos_uploaded', models.PositiveIntegerField(default=0, verbose_name='fotos subidas')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='último uso')),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='última IP usada (anonimizada)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographer_links', to='events.event', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'link de fotógrafo',
                'verbose_name_plural': 'links de fotógrafos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'is_active'], name='link_event_active_idx'), models.Index(fields=['expires_at', 'is_active'], name='link_exp_active_idx')],
            },
        ),
    ]
