# Generated by Django 5.1.15 on 2026-06-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerlink',
            name='featured_image_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='imagen destacada (R2)'),
        ),
    ]
