# Generated by Django 5.1.15 on 2026-06-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZipDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('requester_ip_hash', models.CharField(help_text='sha256 — sin guardar la IP cruda.', max_length=64, verbose_name='hash de IP solicitante')),
                ('photo_ids', models.JSONField(default=list, verbose_name='IDs de fotos')),
                ('photo_count', models.PositiveIntegerField(default=0, verbose_name='cantidad de fotos')),
                ('total_size_mb', models.FloatField(default=0.0, verbose_name='tamaño total (MB)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('ready', 'Lista'), ('failed', 'Falló'), ('expired', 'Expirada')], default='pending', max_length=16, verbose_name='estado')),
                ('zip_key', models.CharField(blank=True, max_length=500, verbose_name='key del ZIP en R2')),
                ('download_url', models.URLField(blank=True, max_length=1000, verbose_name='URL firmada')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira el')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='descargas')),
                ('error_message', models.TextField(blank=True, verbose_name='mensaje de error')),
            ],
            options={
                'verbose_name': 'descarga ZIP',
                'verbose_name_plural': 'descargas ZIP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='zip_status_exp_idx'), models.Index(fields=['requester_ip_hash'], name='zip_iphash_idx')],
            },
        ),
    ]
