# Generated by Django 5.1.15 on 2026-05-21 21:32

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('photographers', '0001_initial'),
    ]

    operations = [
        # Habilitamos pgvector ANTES de crear FaceEmbedding (que usa VectorField).
        # Idempotente: si ya existe, no falla.
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('uploaded_by_admin', models.BooleanField(default=False, help_text='Si True, fue subida por el super admin (no por un fotógrafo).', verbose_name='subida por admin')),
                ('original_key', models.CharField(max_length=500, unique=True, verbose_name='key del original')),
                ('preview_key', models.CharField(blank=True, max_length=500, verbose_name='key del preview')),
                ('thumbnail_key', models.CharField(blank=True, max_length=500, verbose_name='key del thumbnail')),
                ('original_filename', models.CharField(max_length=255, verbose_name='nombre original')),
                ('width', models.PositiveIntegerField(verbose_name='ancho (px)')),
                ('height', models.PositiveIntegerField(verbose_name='alto (px)')),
                ('file_size', models.PositiveBigIntegerField(verbose_name='tamaño (bytes)')),
                ('capture_time', models.DateTimeField(blank=True, null=True, verbose_name='fecha de captura')),
                ('camera_make', models.CharField(blank=True, max_length=100, verbose_name='marca cámara')),
                ('camera_model', models.CharField(blank=True, max_length=100, verbose_name='modelo cámara')),
                ('lens_model', models.CharField(blank=True, max_length=200, verbose_name='lente')),
                ('aperture', models.CharField(blank=True, max_length=20, verbose_name='apertura')),
                ('shutter_speed', models.CharField(blank=True, max_length=20, verbose_name='velocidad obturador')),
                ('iso', models.PositiveIntegerField(blank=True, null=True, verbose_name='ISO')),
                ('focal_length', models.CharField(blank=True, max_length=20, verbose_name='focal')),
                ('exif_raw', models.JSONField(blank=True, default=dict, verbose_name='EXIF crudo')),
                ('status', models.CharField(choices=[('uploading', 'Subiendo'), ('processing', 'Procesando'), ('pending_review', 'Pendiente de revisión'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('deleted', 'Borrada')], default='uploading', max_length=16, verbose_name='estado')),
                ('rejected_reason', models.CharField(blank=True, max_length=255, verbose_name='motivo de rechazo')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprobada el')),
                ('approved_by_admin', models.BooleanField(default=False, verbose_name='aprobada manualmente')),
                ('has_minors_detected', models.BooleanField(default=False, verbose_name='tiene menores detectados')),
                ('has_bibs_detected', models.BooleanField(default=False, verbose_name='tiene dorsales detectados')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='vistas')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='descargas')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.event', verbose_name='evento')),
                ('photographer_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='photographers.photographerlink', verbose_name='link de fotógrafo')),
            ],
            options={
                'verbose_name': 'foto',
                'verbose_name_plural': 'fotos',
                'ordering': ['-capture_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=512, verbose_name='embedding')),
                ('bbox', models.JSONField(blank=True, default=dict, help_text='{x, y, w, h} en porcentaje de la imagen.', verbose_name='bounding box')),
                ('estimated_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='edad estimada')),
                ('is_minor', models.BooleanField(default=False, help_text='True si `estimated_age < 18`. Activa blur en preview público.', verbose_name='es menor')),
                ('last_matched_at', models.DateTimeField(blank=True, null=True, verbose_name='último match')),
                ('match_count', models.PositiveIntegerField(default=0, verbose_name='# de matches')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='photos.photo', verbose_name='foto')),
            ],
            options={
                'verbose_name': 'embedding facial',
                'verbose_name_plural': 'embeddings faciales',
            },
        ),
        migrations.CreateModel(
            name='Bib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('number', models.CharField(help_text="String — puede tener letras (ej. 'A123').", max_length=20, verbose_name='número')),
                ('confidence', models.FloatField(help_text='0.0 a 1.0 (1.0 si fue corregido manualmente).', verbose_name='confianza')),
                ('source', models.CharField(choices=[('ocr_paddle', 'OCR PaddleOCR'), ('ocr_easy', 'OCR EasyOCR'), ('manual_admin', 'Corregido por admin'), ('manual_user_report', 'Reportado por usuario')], max_length=24, verbose_name='origen')),
                ('bbox', models.JSONField(blank=True, default=dict, help_text='Coordenadas en porcentaje de la imagen: {x, y, w, h}.', verbose_name='bounding box')),
                ('is_validated', models.BooleanField(default=False, verbose_name='validado por admin')),
                ('rejected', models.BooleanField(default=False, help_text='Marcado como falso positivo.', verbose_name='rechazado')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bibs', to='photos.photo', verbose_name='foto')),
            ],
            options={
                'verbose_name': 'dorsal',
                'verbose_name_plural': 'dorsales',
                'ordering': ['-confidence'],
            },
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['event', 'status'], name='photo_event_status_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['event', 'status', '-capture_time'], name='photo_event_status_t_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['photographer_link', 'status'], name='photo_link_status_idx'),
        ),
        migrations.AddIndex(
            model_name='faceembedding',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='face_embedding_hnsw_cos', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='faceembedding',
            index=models.Index(fields=['photo'], name='face_photo_idx'),
        ),
        migrations.AddIndex(
            model_name='faceembedding',
            index=models.Index(fields=['last_matched_at'], name='face_lastmatch_idx'),
        ),
        migrations.AddIndex(
            model_name='bib',
            index=models.Index(fields=['number'], name='bib_number_idx'),
        ),
        migrations.AddIndex(
            model_name='bib',
            index=models.Index(fields=['photo', 'number'], name='bib_photo_number_idx'),
        ),
        migrations.AddIndex(
            model_name='bib',
            index=models.Index(fields=['photo', 'is_validated', 'rejected'], name='bib_validation_idx'),
        ),
        migrations.AddConstraint(
            model_name='bib',
            constraint=models.UniqueConstraint(fields=('photo', 'number', 'source'), name='unique_bib_per_photo_source'),
        ),
        migrations.AddConstraint(
            model_name='bib',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0.0), ('confidence__lte', 1.0)), name='bib_confidence_range'),
        ),
    ]
