# Generated by Django 5.1.15 on 2026-06-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='has_faces_detected',
            field=models.BooleanField(default=False, verbose_name='tiene caras detectadas'),
        ),
        migrations.AddField(
            model_name='photo',
            name='needs_minor_review',
            field=models.BooleanField(default=False, help_text='El estimador de edad detectó una cara dudosa (<22). El admin revisa en la cola de aprobación si hace falta blurear.', verbose_name='necesita revisión de menores'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('uploading', 'Subiendo'), ('processing', 'Procesando'), ('processing_failed', 'Falló el procesamiento'), ('pending_review', 'Pendiente de revisión'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('deleted', 'Borrada')], default='uploading', max_length=24, verbose_name='estado'),
        ),
    ]
