# Generated by Django 5.1.15 on 2026-06-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_has_faces_detected_photo_needs_minor_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='hash de contenido'),
        ),
    ]
