# Generated by Django 5.1.15 on 2026-06-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photo_content_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bib',
            name='source',
            field=models.CharField(choices=[('ocr_paddle', 'OCR PaddleOCR'), ('ocr_easy', 'OCR EasyOCR'), ('ocr_gemini', 'OCR Gemini (IA)'), ('manual_admin', 'Corregido por admin'), ('manual_user_report', 'Reportado por usuario')], max_length=24, verbose_name='origen'),
        ),
    ]
